spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.41.128:3306/gulimall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Ware-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.41.128:8848